export default `
*Up to date as of October 10, 2026. The Comptroller's data refreshes yearly, and I read the structure labels from audited statements with AI help and checked them by hand, so this will drift. I may update or rerun it.*

## Hidden costs

On occasion, people get hurt when using a government service. A bus hits a pedestrian. A police officer uses force. An inmate is hurt in jail. When people are injured, they oftentimes sue whoever is responsible, or rather, whoever is readily liable.

Almost every time, those lawsuits end in settlements rather than jury trials. In New York, local governments outside New York City spend several hundred million dollars a year on insurance and on court judgments and claims, and [New York City alone paid about $1 billion](https://comptroller.nyc.gov/newsroom/comptroller-landers-new-dashboard-tracks-city-claims-city-paid-nearly-2b-in-settlements-last-fiscal-year) to settle injury and property-damage claims in fiscal 2024. The direct source of that settlement money varies quite widely depending on who you're suing.

My colleague had a hypothesis about government settlement outcomes. She argued that governments that carry their own liability - i.e., those that are self-insured - pay far more to settle cases than governments that buy insurance coverage. A government paying out of its own budget may look like an easier target to plaintiffs' lawyers, and an insurer handles claims for a living, while for most governments it is a sideline. I thought that was probably right.

## How a government pays its claims

A government has three ways to pay the claims it will someday lose. It can buy a policy from an insurance company. It can join a risk pool, a group of local governments that form their own insurer. Or it can keep the risk, budget a reserve, and write the checks when claims settle. That is self-insurance, and most large governments do it.

In New York, nearly a thousand of the state's roughly 1,600 general-purpose local governments belong to one pool, the New York Municipal Insurance Reciprocal, or NYMIR. When a town insured through NYMIR is sued, the town is the defendant but NYMIR handles and pays the claim, keeping the first $750,000 of each loss and passing the rest to its own insurers.

When Nassau County is sued, Nassau is both defendant and payer. In 2024 it paid $43 million in lawsuit judgments and settlements out of its own budget.

## Comparing the bills

New York is the place to test it. Every county, city, town, and village outside New York City reports its insurance and its judgments and claims to the State Comptroller, in files going back to 1995. I read the risk-management note in the audited statements of all 57 counties and the largest cities, towns, and villages, 135 governments in all, then compared them over 2015 to 2024.

<sic-core-chart></sic-core-chart>

Each of the 109 marks is a government whose audited statements I read. Counties spend less per resident than cities, towns, and villages. Within each kind the dark marks (governments that carry their own liability) and the light marks (governments that buy coverage) overlap, but the typical dark mark sits higher.

Comparing each government only with others of its type and size, the self-insured spent about a fifth more than the covered. The range the data allow runs from about 0.8 times to about double. Counties and towns alone come out closer to even. Large cities barely enter the test, since the largest city I read that buys coverage, Schenectady, has about 67,000 residents.

The best estimate leans my colleague's way, and the books flatter the self-insured, whose lawyers are paid from other lines. A fifth more falls short of far more, though, and the range leaves room for no gap at all. Among cities and villages the self-insured do seem to pay more, but there are only eight covered ones to compare them with, too few to say how much. The clearer difference is in how much the bill swings.

## What goes with a bigger bill

The hypothesis assumes a government that pays its own claims draws more of them, or bigger ones. In the books, the bill tracks the type of government and whether it runs a police department. A government that runs its own police department spends roughly 2.4 times as much per resident on liability as one of the same type and size that does not, anywhere from 1.7 to 3.3 times as much. Holding those equal, the self-insured still come out somewhat higher, with ranges that include no difference.

The hypothesis also assumes insurers and pools handle claims better than governments do. Even if they do, a pool may not price each member closely. Tom Clark, a political scientist at Stanford, traces how that played out in Vallejo, California, in [a 2026 working paper](https://www.tomclarkphd.com/files/police_insurance.pdf). Vallejo paid each claim up to $500,000 itself, and its pool, which charged members largely by payroll, paid the rest, so a city whose claims ran more than two and a half times what the pool expected paid everyone else's rate. In late 2017 the pool voted to raise Vallejo's share of each claim to $2.5 million, and the city moved to what Clark calls market-based coverage, with a $2 million deductible. Its premium went from $392,000 to $2.4 million by 2024, and Clark finds its police cleared more violent crimes after the switch.

There is a lot I cannot see, such as whether self-insurers settle each claim more generously or whether politics shapes their settlements. And a government with a bad record can be priced out of a pool, as Vallejo was, and would show up here as a costly self-insurer.

## What coverage buys

Coverage buys you a bill that you can plan around. Comparing governments of the same type and size, self-insured governments' bills swing nearly twice as much from year to year as covered governments', and more in every type of government. A covered government's bill is mostly a steady premium. What it still pays itself is as lumpy as anyone's, but small next to the premium.

<sic-volatility></sic-volatility>

The typical self-insurer's worst year in the decade cost about twice its average, against about 1.4 times for a covered government. Against the whole budget the stakes are modest, since the typical self-insurer's worst year added about 0.8 percent of its spending, more for small governments than large ones.

## What a government could do

New York City's ClaimStat and Chicago's 2019 review both recommend reading the claims data and acting on what it shows.

Joanna Schwartz, a law professor at UCLA, studied how 100 jurisdictions pay for police lawsuits in [a 2016 article](https://www.uclalawreview.org/wp-content/uploads/2019/09/Schwartz-63-5.pdf), and one risk-pool expert she interviewed estimated that governments under about 100,000 residents generally pool or buy insurance. A government that small gets a steadier bill in a pool and, if anything, pays less for it.

Every county larger than Albany County, about 312,000 people, carries its own liability, and so does every town, city, and village larger than the biggest of its kind that buys coverage, where the statements are clear. Together they hold about a third of the liability dollars the books show outside New York City. Public books cannot say whether coverage stops being worth buying at that size or stops being offered. Either way, a government that big is its own insurer, and I think it should run its claims the way an insurer would.

The closest evidence comes from public hospitals that pay their own malpractice claims, where telling patients about errors and offering to settle early closed claims faster and cut legal bills without raising payouts, though a 2024 review rates the evidence on such programs as very weak overall. New York City's public hospitals took over their own malpractice claims and defense in the 2000s, and their payouts fell about a third from a 2003 peak while the police department's rose 60 percent. Malpractice payments fell nationally over the same years, so I cannot say how much of that the change explains. The aim is to settle fair claims sooner and fix their causes. The risk is a claims office that fights injured people harder.

## Housekeeping

Every label, with its source and quote, is in the downloads above. The code is [public](https://github.com/eichenbaumj/gizmowarehouse.org/tree/main/gizmos/self-insurance-cost). If a number is wrong, tell me at joe@group17a.com. My firm, 17A, helps governments build this kind of capacity. Nobody paid for this piece.

<details id="methodology">
<summary class="font-serif text-2xl font-bold text-cobalt cursor-pointer select-none mt-8 mb-4">Methodology</summary>

**Data.** New York State Comptroller, Financial Data for Local Governments, account-level files for counties, cities, towns, and villages, fiscal years 1995 to 2026. Liability cost = Unallocated Insurance (1910) + Judgments and Claims (1930) + Property Loss (1931), plus Excess Insurance (1722) where a government's statements show it buys liability excess coverage. A government's internal self-insurance funds count only where its own statements show they pay liability, and operating-fund charges into those funds are left out so nothing counts twice; each coded line, with its quote and page, is in the code. Workers' compensation, employee health, and self-insurance administration are out. Per resident (Census estimates), in 2024 dollars. Total spending excludes interfund transfers, debt principal, and, from 2020, the custodial fund that passes taxes collected for counties and school districts through to them. The opening's statewide figure sums the same lines for counties, cities, towns, and villages, fiscal 2022 to 2024, in current dollars: $486 million, $598 million, and $569 million as booked, or $297 million to $436 million with the governments whose judgments lines carry tax refunds or employee health claims left out. New York City's fiscal 2024 figure is its injury and property-damage claims ($1.04 billion) within $1.94 billion of all resolved claims. Federal Transit Administration, National Transit Database, casualty and liability expense (object class 506), service, and ridership, 2022 to 2024, directly operated full reporters.

**Labels.** Every county outside New York City, the 20 largest cities, the 30 largest towns, and the 10 largest villages by 2015 to 2024 average population, plus 18 more read along the way (135 in all), each labeled from the risk-management note (GASB Statement 10) in its most recent audited statements (fiscal 2024 for most) and recorded with the document, page, and a verbatim quote. I read them with AI help and checked them by hand. A premium-only signature, tested as a label for governments I did not read, agreed with the documents only about 60 percent of the time, so it is not used. A stated liability retention above $100,000 is treated as self-insurance and one at or below it as a deductible, whatever the note calls the arrangement. The NYMIR subscriber list (July 2026) describes pool membership only. Twenty-three governments whose own notes say they keep their liability are on it, buying other lines there, and the notes govern; Putnam County, which buys a NYMIR policy with a $250,000 liability deductible, counts as self-insured under the $100,000 rule.

**Held out.** Twenty-four labeled governments are left out because their books cannot carry the comparison, and the chart lists each with its reason. Their judgments line carries other payments (Nassau's is about half property-tax refunds; Cattaraugus's carries its health plan; a few others show a large line that barely moves, the mark of benefit claims or tax refunds). Or they self-insure but their documented liability claims exceed everything the Comptroller's lines show for liability, or show no claim payments in ten years. Or they buy coverage but book premiums on department lines (under $1 a resident of unallocated insurance). Two more, Ithaca and Mount Vernon, have fewer than eight years of filings.

**Comparison.** Each government's 2015 to 2024 average, compared within type and population band (2,500 to 10,000; 10,000 to 50,000; 50,000 to 150,000; 150,000 and up). The ratio averages the within-band gaps between self-insured and covered means, weighting each band by its number of self-insured governments, with each government's average capped at the 99th percentile of its type; the range is from a county-clustered bootstrap with 2,000 draws. Before running it I planned to match on region as well; that leaves 52 governments with a peer and gives 1.23 (0.82 to 1.81). Judgments and claims alone come out 2.95 times (range 1.25 to 7.69) and premiums alone 0.65, since covered governments pay most of their claims through premiums. Other versions: counties and towns only, 1.07 (0.72 to 1.81); typical (median) governments, 1.20; a regression with size, police, capital spending, type, and region, 1.12 (0.83 to 1.53); all funds as booked, 1.22 (0.61 to 2.45); operating funds only, 0.69 (0.30 to 1.14), which drops the funds many self-insurers pay their claims from; lines whose purpose the statements leave unclear left out, 1.13 (0.68 to 1.81); 2015 to 2019, 1.19; 2020 to 2024, 1.28; adding each government's law department, 1.26; counting claims owed but not yet paid instead of cash paid, 1.56, though for many governments that liability also holds workers' compensation. The books flatter self-insurers twice over: their lawyers and reserves sit on other lines, and a covered government's premium includes the insurer's overhead (about 27 cents of each premium dollar at NYMIR in 2016 to 2020, per the state's examination).

**Swing.** For each government, the standard deviation of its yearly liability cost per resident over 2015 to 2024 divided by its average, then medians by group: 51 percent for the self-insured and 23 percent for the covered. Within type and population band the self-insured swing 1.8 times as much (range 1.1 to 2.7); with type and size held equal in a regression, 1.8 times (range 1.3 to 2.5). The worst year is the single highest year over the government's own average. A covered government's bill is mostly premium (90 percent at the median), and what it still pays itself moves as much as a self-insurer's claims. Where a self-insurer pays claims from a reserve or internal fund, the swing measured here is in what the fund pays out; steady contributions to the fund can smooth the hit to the budget, though the government still carries the bad years. A government with a year below zero (a reserve release booked as a negative claim; Onondaga County) has no meaningful average and is left out of this measure.

**Police.** A police department means municipal police spending (account 3120) of at least 1 percent of total spending; counties book their sheriffs under 3110, and only Westchester among the compared counties runs a county police department. In a regression of liability cost per resident on type, size, capital spending, structure, and whether a government has a police department, a department goes with 2.36 times the cost (range 1.70 to 3.27). Within a type, that contrast rests mostly on towns (22 of 33 compared towns have a department; nearly every city and village does). Among governments with a department, a bigger police share of the budget goes with only a slightly bigger bill (1.23 times per ten points, range 0.87 to 1.75). In the same regressions the self-insured come out 1.18 to 1.25 times higher, with ranges that include no difference, and structure adds almost nothing to the fit (R-squared 0.549 with it, 0.543 without). These are associations, not effects. Splitting by police department, or counties by sheriff and jail spending, gives ranges that all include no difference (among governments with a department, 1.66, range 0.98 to 2.82); cities and villages together lean toward the self-insured paying more (2.27 times in a regression, range 1.17 to 4.43; 1.57 matched within type and size), with eight covered governments.

**Transit.** Of the 100 largest directly operated agencies, 90 have readable labels. Adjusted for size, the self-insured spend 1.43 times as much on casualty and liability per vehicle revenue mile (range 0.99 to 2.06), 0.99 times per passenger trip, and 1.01 times as a share of operating cost. No covered agency is as large as the 36 biggest self-insured ones, so size, structure, and state law move together; this is a description, not a test.

**Largest governments.** The share that self-insure rises with size, from about a quarter under 50,000 residents to all six above 500,000. The largest covered county, town, city, and village are Albany County (about 312,000), Ramapo (about 144,000), Schenectady (about 67,000), and Kiryas Joel (about 32,000), and every labeled government above those sizes whose statements are clear carries its own liability. (Ramapo's note describes a $50,000 deductible, yet its general-liability fund paid $2.5 million of claims in 2023, so I am uncertain it belongs with the covered.) Stated retentions rise with size: the median is $1 million at 100,000 to 500,000 residents, and the two above 500,000 that state one keep $2 million (Monroe) and $10 million (Suffolk). Those 23 governments hold about 33 percent of liability cost as booked outside New York City. That leaves out the governments whose judgments lines carry refunds or benefits, Nassau and Islip among them, and Suffolk, Erie, Hempstead, and Brookhaven book claims elsewhere, so it is an undercount. The evidence on in-house claims work: Kachalia and colleagues (2010) and LeCraw and colleagues (2018) on public hospitals; Schultz and colleagues (2024) on the strength of that evidence; the Citizens Budget Commission (2014) on New York City's hospitals and police. The guardrail that capacity can be turned against claimants comes from Los Angeles County's inspector general (2024).

**What the comparison cannot do.** It cannot say what a large self-insured government would pay with an insurer, because none in New York buys coverage from the first dollar. It cannot separate the effect of self-insuring from selection into it, since a government with a bad record can be priced out of a pool, as Vallejo was, and would then show up here as a costly self-insurer. It holds New York's tort law constant and does not travel. It compares spending as booked, not pure loss.

</details>

<details>
<summary class="font-serif text-2xl font-bold text-cobalt cursor-pointer select-none mt-8 mb-4">Sources</summary>

- New York State Comptroller, Financial Data for Local Governments (account-level bulk files).
- New York City Comptroller, claims dashboard release, April 30, 2025 (fiscal 2024: $1.04 billion in injury and property-damage claims within $1.94 billion across 13,397 resolved claims).
- Nassau County, 2024 Annual Comprehensive Financial Report (suits and damages, $42.9 million; tax certiorari refunds, $43.9 million).
- Audited financial statements of each labeled government (Federal Audit Clearinghouse and government websites), cited row by row in the labels download.
- NYMIR subscriber list by county, as of July 31, 2026; NY Department of Financial Services examination report on NYMIR as of December 31, 2020.
- Federal Transit Administration, National Transit Database, 2022 to 2024.
- Joanna Schwartz, "How Governments Pay: Lawsuits, Budgets, and Police Reform," 63 UCLA Law Review 1144 (2016). John Rappaport, "How Private Insurers Regulate Public Police," 130 Harvard Law Review 1539 (2017). Tom Clark, "Municipal Liability Insurance as Police Oversight: Evidence from Vallejo, California," working paper, April 2026.
- Kachalia, Kaufman, Boothman, and colleagues, "Liability Claims and Costs Before and After Implementation of a Medical Error Disclosure Program," Annals of Internal Medicine 153(4) (2010). Schultz, Zhou, Gray, and colleagues, "Patient characteristics of, and remedial interventions for, complaints and medico-legal claims against doctors: a rapid review of the literature," Systematic Reviews 13:104 (2024). Schaffer and colleagues, "Rates and Characteristics of Paid Malpractice Claims Among US Physicians by Specialty, 1992-2014," JAMA Internal Medicine 177(5) (2017). LeCraw, Montanera, Jackson, and colleagues, "Changes in liability claims, costs, and resolution times following the introduction of a communication-and-resolution program in Tennessee," Journal of Patient Safety and Risk Management 23(1) (2018).
- Elizabeth Wyner, Citizens Budget Commission, "Controlling the Cost of New York City's Settlements and Judgments: A Tale of Two Agencies," August 2014. Los Angeles County Office of Inspector General, "Reform and Oversight Efforts: Los Angeles County Sheriff's Department, October to December 2023," February 2024.
- New York City Comptroller, ClaimStat (2014 to date). Chicago City Council Office of Financial Analysis, "Chicago's Lawsuit Costs," 2019.
- Christian Science Monitor, "Cities pool their risks and insure themselves," June 20, 1986. Governing, "Massive Legal Costs Weigh on Local Budgets," October 2016.
- Matthiesen, Wickert & Lehrer, municipal governmental immunity and tort liability chart, February 2022.

</details>
`;
